### ISSUE TITLE
Generating CSS source code from the rule tree.

### ISSUE THREAD

**Issue by saabi** [tabatkins/parse-css#24]
Hey Tab,

I believe you're aware of vminpoly which adds vw, vh, vmin & vmax units functionality as a  prolly.

After talking a bit with Brian Kardell, I'm working on extending the basic architecture to support pluggable prollyfills on top of your parser/tokenizer. To make it suit my needs I modified tokenizer.js a bit so that it can generate CSS source code adding the toSourceString() function in the various token's prototypes. For example (some Git diff output):

``` javascript
 DimensionToken.prototype.toString = function() { return "DIM("+this.num+","+this.unit+")"; }
 DimensionToken.prototype.toSourceString = function() { return this.num+this.unit; }
// ...
NumberToken.prototype.toString = function() {
    if(this.type == "integer")
        return "INT("+this.value+")";
    return "NUMBER("+this.value+")";
}
NumberToken.prototype.toSourceString = function() {
    if(this.type == "integer")
        return this.value;
    return this.value;
}
```

Perhaps we can add and maintain .toSourceString() directly in your repository. This addition could be generally useful so perhaps it does belong inside tokenizer.js

What do you think?

EDIT:
Well, it has been a while since I've looked at vminpoly and, after refamiliarizing myself with it again, I've realized part of the CSS source code generation is in vminpoly itself. So .toSourceString() won't generate complete source code. 

More so, I'm hooking into parts of the code generator to filter out unneeded parts of the rule tree, so a code generator embedded in your library won't be useful to me unless it can call back at different points during the code generation.

Still, perhaps it could be worthwhile to put a simplified version of vminpoly's CSS code generator into your parser for other people. Let me know if you're interested and I'll show you the relevant parts in my code.

And then again, perhaps a hookable code generator could be neat as well, though it would be more complex to implement in a generic reusable way.

**Comment by ocwal** [comment]
Any update on this?

**Comment by tabatkins** [comment]
For some reason I'd gotten as far as adding `.toSource()` to all the token types some time ago, but never finished up the rules; I think because it needed structural knowledge at the time. That's no longer the case, so now everything has a `.toSource()` method that should reserialize things properly.

I know that I'm not currently correctly implementing the "put comments between certain tokens" logic, so if you use comments instead of whitespace, or construct objects directly rather than from parsing, it might output incorrect source that won't roundtrip the same. I'll fix that later.
